### ISSUE TITLE
deploy error occurred, message: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ZhangYanTJU** [yanglbme/gitee-pages-action#10]
你好，感谢开发这样的工具！
我使用中遇到一个问题：
![Annotation 2020-08-23 085104](https://user-images.githubusercontent.com/23287501/90972970-04c4b000-e51e-11ea-9420-a6a071c1bbb9.png)
执行报错：
deploy error occurred, message: 'NoneType' object has no attribute 'group'
其它方面开始没有问题，绑定的微信公众号也提示正常登陆了gitee。
结果就是并没有成功帮我点击gitee里边的更新按钮。

**Comment by yanglbme** [comment]
@ZhangYanTJU  谢谢反馈，是否区分大小写依赖于与 Gitee 自身的实现，并不由 Gitee Pages Action 决定。

**Comment by tan-huang** [comment]
在gitee的`Settings`-`Profile`-`Repository path`中查看仓库名。即“gitee.com/”后面的内容。
