### ISSUE TITLE
迁移库失败

### ISSUE THREAD

**Issue by okraX** [yanglbme/gitee-pages-action#11]
本地的机器能通过SSH Key 正常访问gitee，但配置在GIthub那边，操作 Github Action 报错，提示 Permanently added 'github.com,140.82.121.3' (RSA) to the list of known hosts.

**Comment by yanglbme** [comment]
确定报错是吗？`SSH_PRIVATE_KEY` 配置有问题吧

**Comment by yanglbme** [comment]
贴一下报错日志

**Comment by okraX** [comment]
解决了，生成 SSH_PRIVATE_KEY 的时候，不要输入密码，就可以正常迁移仓库了。

**Comment by yanglbme** [comment]
ok
