### ISSUE TITLE
请求大佬支援，sync to gitee报错

### ISSUE THREAD

**Issue by xytx-dr-z** [yanglbme/gitee-pages-action#18]
在多次语法错误后终于跑通一半，又遇到这个错误，找不到原因，是我的公钥有错误吗？请求指点。谢谢大佬。
日志：https://github.com/xytx-dr-z/xytx-dr-z.github.io/actions

![image](https://user-images.githubusercontent.com/73154691/96675888-94f86780-139e-11eb-9c5b-705e57a224a5.png)

**Comment by yanglbme** [comment]
source-repo 配置错了吧，应该是 `git@github.com:xytx-dr-z/xytx-dr-z.github.io.git`

**Comment by xytx-dr-z** [comment]
改过了  依然报错 
![image](https://user-images.githubusercontent.com/73154691/96683037-34702700-13ac-11eb-8c14-006d5903f4a4.png)
![image](https://user-images.githubusercontent.com/73154691/96683083-42be4300-13ac-11eb-93ae-bcbe836157c0.png)

**Comment by yanglbme** [comment]
根据 Actions 的错误信息 `Your push would publish a private email address.` 搜索。

**Comment by xytx-dr-z** [comment]
终于跑通了，经过以上错误之后又出现了新的问题，然后在大佬 @yanglbme 提醒我 [搜索](https://github.com/yanglbme/gitee-pages-action/issues/18#issuecomment-713352343)   以后，我度娘到 [CSDN静待心明
的解决方案](https://blog.csdn.net/qq_34359927/article/details/83860031)。
然而并没有什么卵用，
继续往下找发现一篇[码云「邮箱隐私保护」和「禁止命令行推送暴露个人邮箱」 ...](https://www.oschina.net/news/111153/gitee-private-email-protected) 中提到相似错误，
转到码云并做出如下设置（我之前选择了不公开我的邮箱，汗）：
![image](https://user-images.githubusercontent.com/73154691/96689145-992f7f80-13b4-11eb-9164-d61c4dcc0375.png)

问题解决

感谢 @yanglbme 大佬技术支持~

**Comment by yanglbme** [comment]
@xytx-dr-z 好的，你也反馈了一个新的问题，我觉得值得记录下来给其他人参考。

**Comment by ym6** [comment]
还有一种情况会导致sync to gitee在第8步报错，就是GitHub上没有设这SSH keys，设置跟gitee上一样的id_rsa公钥后可以正常运行。

**Comment by yanglbme** [comment]
@ym6 谢谢反馈
