### ISSUE TITLE
gitee pages 没有重新部署

### ISSUE THREAD

**Issue by packyzbq** [yanglbme/gitee-pages-action#20]
你好~ 我的action里，所有步骤都执行成功了，但是gitee pages没有重新部署，这种情况怎么看日志或者debug呢
--- 更新 ---
我尝试直接执行 python，发现在login 就报错推出了

**Comment by yanglbme** [comment]
在哪个仓库？

**Comment by yanglbme** [comment]
直接执行 python 脚本报了什么错？

**Comment by packyzbq** [comment]
> 直接执行 python 脚本报了什么错？

只打印了 ::set-output name=result::False，是在login() 最后返回的`return '个人主页' in resp.text or '我的工作台' in resp.text` 报错。登录页面好像是错的

**Comment by yanglbme** [comment]
注意事项有看了吗？

> 如果在使用过程中遇到了 Gitee 短信验证码导致 Gitee Pages Action 无法自动登录部署 Pages，参考 #6 。

**Comment by packyzbq** [comment]
感谢！已解决，很好奇为什么微信绑定了，就不会需要验证码和短信了呢？
