### ISSUE TITLE
 gitee-repo: doocs/advanced-java是仓库/分支这样的格式吗？

### ISSUE THREAD

**Issue by SaulJWu** [yanglbme/gitee-pages-action#21]
# 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
gitee-repo: doocs/advanced-java

请问是仓库/分支这样的格式吗？

**Comment by yanglbme** [comment]
与分支无关。

gitee-repo 的格式是：`user(organization)/repo`，如 `yanglbme/gitee-pages-action`，或 `doocs/advanced-java` 等等。

**Comment by SaulJWu** [comment]
> 与分支无关。
> 
> gitee-repo 的格式是：`user(organization)/repo`，如 `yanglbme/gitee-pages-action`，或 `doocs/advanced-java` 等等。

好的，非常感谢！
