### ISSUE TITLE
为什么Gitee pages自动把部署分支放到了master？

### ISSUE THREAD

**Issue by SaulJWu** [yanglbme/gitee-pages-action#22]
是这样，我用两个分支，分别来保存源码和静态文件。

其中master是源码，gh-pages是部署分支。

每当现在sync.yml同步成功后，部署分支就变成了，master。

是不是gitee-pages-action，部署分支也要写成gh-pages呢？如果是这样，那么源码不会自动同步到gitee吗？

**Comment by yanglbme** [comment]
`branch` 参数默认是 `master`，如果你是部署在其它分支，如 `gh-pages`，需要指定一下：`branch: gp-pages`

**Comment by SaulJWu** [comment]
> `branch` 参数默认是 `master`，如果你是部署在其它分支，如 `gh-pages`，需要指定一下：`branch: gp-pages`

好的，我的问题是，我设置了部署分支，虽然会部署到gitee的指定分支上，但是我的源码还需要自己手动同步到master对吗？

**Comment by yanglbme** [comment]
你说提交到 gitee 的 master？不需要的，`wearerequired/git-mirror-action@master` 这个 action 会将你整个仓库(所有分支)同步到 gitee。

**Comment by SaulJWu** [comment]
> 你说提交到 gitee 的 master？不需要的，`wearerequired/git-mirror-action@master` 这个 action 会将你整个仓库(所有分支)同步到 gitee。

好的，感谢作者，非常感谢您百忙之中抽出时间回到我这个小白︿(￣︶￣)︿，这个issue可以关了

**Comment by yanglbme** [comment]
好的，有问题欢迎随时反馈。

**Comment by afc163** [comment]
这是个 breaking change 呀，之前 AntV 都没配这个的。

**Comment by afc163** [comment]
我们手动给 AntV 各库都补上 branch: gh-pages 吧。

@xingwanying @BBSQQ

**Comment by yanglbme** [comment]
@afc163 非 master 分支，请指定 branch。

目前考虑到老用户也有使用默认 master 分支的情况，如果 action 中修改默认部署分支为 master/main，会有问题。
