### ISSUE TITLE
偶现 Gitee Pages 部署失败

### ISSUE THREAD

**Issue by chenjiahan** [yanglbme/gitee-pages-action#26]
在实际使用过程中发现，Gitee pages 会出现部署失败的情况，错误文案为「Could not read from remote repository.」，大约 1~2 周就会出现一次，导致网站 404。

出现该问题后，手动点击「更新」按钮，即可恢复。

### 截图

![image](https://user-images.githubusercontent.com/7237365/101598563-53e21280-3a33-11eb-916b-67791a7c04e8.png)

### 配置文件

https://github.com/youzan/vant/blob/dev/.github/workflows/sync.yml

**Comment by yanglbme** [comment]
@chenjiahan 谢谢反馈。最近两周有出现这个问题吗？

gitee-pages-action 默认部署的分支是 master，如果是其他分支，如 `gh-pages`，是需要指定的。

若是指定了错误的分支(或者不配置，默认 master)，而项目里 pages 的代码并不是在错误分支(或者 master)，站点就有会问题。

上次我给 vant 提 PR 修复了：https://github.com/youzan/vant/commit/de10a2a956ed6a6a812232d935fd02288f1d5122

**Comment by yanglbme** [comment]
2.x 分支的配置文件也需要改一下

**Comment by yanglbme** [comment]
https://github.com/youzan/vant/pull/7713

**Comment by chenjiahan** [comment]
感谢排查，可能是 2.x 分支配置未更新导致的👌

**Comment by chenjiahan** [comment]
今天 vant-weapp 仓库也有出现该问题，我看了下，vant-weapp 仓库的 branch 是配置正确的，所以可能存在其他原因

https://github.com/youzan/vant-weapp/blob/dev/.github/workflows/sync.yml

**Comment by yanglbme** [comment]
我想确认一下，出现“部署失败: Could not read from remote repository”的错误，是否会导致站点 404？

**Comment by chenjiahan** [comment]
会导致站点 404 喔

**Comment by yanglbme** [comment]
我检查了 vant 以及 vant-weapp 的配置，都没问题了。后续麻烦留意一下有没有同样的情况。

**Comment by chenjiahan** [comment]
好的，我再观察一下

**Comment by gamecss** [comment]
或许是gitee pages有某种风控系统？
