### ISSUE TITLE
部署gitee出错

### ISSUE THREAD

**Issue by lieber68** [yanglbme/gitee-pages-action#27]
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/17981721/102091617-0a8e2a80-3e5a-11eb-8118-9652f85cdc91.png">
<img width="626" alt="image" src="https://user-images.githubusercontent.com/17981721/102091736-34475180-3e5a-11eb-8836-f0eb01311c38.png">

**Comment by yanglbme** [comment]
你可以 re-run 试试

**Comment by lieber68** [comment]
感谢 后面重新运行可以了
