### ISSUE TITLE
如何确认是否更新成功

### ISSUE THREAD

**Issue by yi-Xu-0100** [yanglbme/gitee-pages-action#28]
使用后，workflows 中显示为成功，但是我发现没法确认是否更新。而且点开 gitee 对应的page页面，是没有更新的，仓库已经更新完了。

想知道怎么确定它是否完成更新呢？

<https://github.com/yi-Xu-0100/purewriter-FAQ/runs/1616231569>

<https://gitee.com/yiXu0100/purewriter-FAQ>

**Comment by yanglbme** [comment]
actions 显示成功是表示已经触发更新了，可能正在更新，更新完之后，站点还需要刷新浏览器缓存。

这个是没法确定站点是否更新完毕的。一般来说，actions 成功后一分钟内就会更新完毕。

**Comment by yi-Xu-0100** [comment]
@yanglbme 我想现在已经过了1分钟了，甚至很长时间了。然后网页我从无痕浏览页面访问也是没有刷新。

我不知道是什么情况， GitHub 这边都更新好了。

emmm，后面再看看情况吧。

**Comment by yi-Xu-0100** [comment]
好像知道啥问题了，我复制我上一个使用的测试仓库的配置，没改 `gitee-repo` 😅

**Comment by yanglbme** [comment]
行，参数一定要配置正确。

**Comment by yi-Xu-0100** [comment]
好像不是这个问题，我修改了 `gitee-repo` 字段，很注意相应的大小写。填写的是我 gitee 对应的仓库，但是仍然是成功的返回，但是对网页端没有没有任何更新。是否能够设置使用 debug 字段给出更多的信息排除相应的问题。

**Comment by yi-Xu-0100** [comment]
斯……我又又又确认了下，可能是我的缓存问题，我以为用无痕看的，其实不是！(逃🤐

**Comment by yanglbme** [comment]
那现在 Gitee Pages 更新了是吧？

**Comment by yi-Xu-0100** [comment]
@yanglbme 应该是没问题了，后续几天看看效果，现在最后一次的更新不是我手动按的，应该是成功的。

**Comment by yanglbme** [comment]
ok，一般配置没问题的话，都能自动更新。我自己很多项目里都在使用。
