### ISSUE TITLE
GITEE_RSA_PRIVATE_KEY的问题

### ISSUE THREAD

**Issue by HuBoZhi** [yanglbme/gitee-pages-action#29]
Cloning into bare repository 'MarkdownBook.git'...
SOURCE=git@github.com:HuBoZhi/MarkdownBook.git
DESTINATION=git@gitee.com:hubozhi/markdown-book.git
Warning: Permanently added 'github.com,140.82.113.3' (RSA) to the list of known hosts.
Load key "/root/.ssh/id_rsa": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

这个GITEE_RSA_PRIVATE_KEY是公钥还是私钥，这个是怎么生成的，为什么我看到还有人放在了另一个配置里面。
教程可否在详细一些。感谢大佬回答，知识量太少看不懂你这个教程。

**Comment by yanglbme** [comment]
回答两个问题：

1. PRIVATE 表示私有的，说明这是一个私钥。私钥配置在 GitHub，而公钥配置在 Gitee。

这就相当于，你在本地电脑上保存了私钥，公钥放在 Gitee 上，然后你在本地提交代码到了 Gitee。

只不过你现在的代码是在 GitHub 上，依靠 GitHub 帮你自动同步最新的代码到 Gitee 而已。

2. 密钥的生成

```bash
ssh-keygen -t rsa
```

**Comment by yanglbme** [comment]
https://gitee.com/help/articles/4181#article-header0

**Comment by HuBoZhi** [comment]
感谢，我继续研究一下

**Comment by yanglbme** [comment]
![image](https://user-images.githubusercontent.com/21008209/105623234-34703f00-5e53-11eb-8bf6-114e72c831aa.png)

我的公钥是放在这里。

**Comment by yanglbme** [comment]
我在 README 中更新了公私钥的完整配置步骤，你可以参考一下 @HuBoZhi

**Comment by HuBoZhi** [comment]
好的



---原始邮件---
发件人: "Yang Libin"<notifications@github.com&gt;
发送时间: 2021年1月26日(周二) 凌晨1:25
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;;
抄送: "双子螺狮"<1310225330@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [yanglbme/gitee-pages-action] GITEE_RSA_PRIVATE_KEY的问题 (#29)




 
我在 README 中更新了公私钥的完整配置步骤，你可以参考一下 @HuBoZhi
