### ISSUE TITLE
码云登录需要验证码

### ISSUE THREAD

**Issue by jupitersh** [yanglbme/gitee-pages-action#3]
邮箱提示在非常用IP登录，然后有个登录验证码

**Comment by yanglbme** [comment]
@jupitersh 我记得我在最初开发这个 GitHub Action 的过程中也遇到了这个问题，我登录 Gitee 官网，发现需要验证码，输入验证码并成功登录之后，再使用 gitee-pages-action，好像就可以了，你不妨试试？

**Comment by jupitersh** [comment]
噢 谢谢 我试试

**Comment by yanglbme** [comment]
参考 #6
