### ISSUE TITLE
Error: Unknown error occurred in login method, resp: <!DOCTYPE html>

### ISSUE THREAD

**Issue by liu-lihao** [yanglbme/gitee-pages-action#37]
![image](https://user-images.githubusercontent.com/43512998/126824210-2bd99cd8-cd4e-4645-bf47-d54c0fd2e45c.png)
![image](https://user-images.githubusercontent.com/43512998/126824455-7d971bf3-4549-4dbc-b634-f7cca876fb8e.png)

**Comment by yanglbme** [comment]
你好，我看了你的 html 报错文件，发现是你帐号登录时需要短信验证码校验，以确认是本人。

解决方案是：关注 Gitee 微信公众号，绑定你的 Gitee 帐号，然后就可以接受登录提示，并且不需要短信验证码校验。

![image](https://user-images.githubusercontent.com/21008209/126853852-4bf99f37-d738-48d3-b8bc-b3f56e25691c.png)
