### ISSUE TITLE
Error: Need phone captcha validation, please follow wechat official account "Gitee" to bind account to turn off authentication.

### ISSUE THREAD

**Issue by iwyang** [yanglbme/gitee-pages-action#38]
出错：Error: Need phone captcha validation, please follow wechat official account "Gitee" to bind account to turn off authentication.

警告：第三方内容检测服务判别此内容可能违规，服务暂时停用，请通过 Q 群 1050025484 申诉。

**Comment by yanglbme** [comment]
@iwyang 关注 Gitee 服务号，绑定你的 Gitee 帐号试试~

**Comment by yanglbme** [comment]
Gitee Pages 服务停用问题，可以联系 Gitee 官方处理哈~

**Comment by iwyang** [comment]
谢谢，搞定了。

**Comment by adayim** [comment]
> 谢谢，搞定了。

这个是怎么搞定的？能说一下吗？非常感谢，我也遇到了同样的问题：
`Need phone captcha validation, please follow wechat official account "Gitee" to bind account to turn off authentication.`
是需要解除手机绑定吗还是怎么操作？没有找到关闭短信验证的地方。
