### ISSUE TITLE
关于SSH密钥配置

### ISSUE THREAD

**Issue by CharesFang** [yanglbme/gitee-pages-action#39]
额，其实是一个小小的建议。在我没有理解错的情况下，Gitee和Github的同步实际上是依赖于Gitee账户和Github账户都配置于同一个密钥对的情况；即Gitee和Github账户都是使用的同一个公钥进行认证，可否在readme.md中说明更清楚一点？当时配置的时候给Github和Gitee配了不同的密钥对死活认证不了，可能存在一定的阅读误解）

**Comment by yanglbme** [comment]
好的，谢谢你的建议。我看看怎么写哈

**Comment by CharesFang** [comment]
谢谢您采纳我的建议。
