### ISSUE TITLE
actions只能使用一次

### ISSUE THREAD

**Issue by BayMRX** [yanglbme/gitee-pages-action#4]
在使用hexo部署到github之后，仓库里创建的`.github/workflows`目录会被删除，就没法同步部署到gitee中，不知该怎样解决？

**Comment by yanglbme** [comment]
@BayMRX 不是被删除了，是因为你 `.github/workflows` 放的位置不对，导致 hexo 自动部署时，没有将  `.github/workflows` 上传到 GitHub。

**Comment by BayMRX** [comment]
那可否请教一下这个文件夹应该放在哪里呢，我是放在了博客根目录的`/source`文件夹

**Comment by yanglbme** [comment]
这个属于 hexo 使用的问题哈，可以自己研究一下
