### ISSUE TITLE
未修改过任何配置，突然今天不能部署了

### ISSUE THREAD

**Issue by Kaiyiwing** [yanglbme/gitee-pages-action#40]
一直未修改过配置，但今天突然部署失败

相关信息如下

![image](https://user-images.githubusercontent.com/44634134/131457285-5e43b82f-e32e-4ee1-b648-fb129956936d.png)

![image](https://user-images.githubusercontent.com/44634134/131457338-814c07f4-910a-4533-bf78-e234e362b667.png)

**Comment by yanglbme** [comment]
我看看问题，马上修复一下哈

**Comment by yanglbme** [comment]
Gitee 网站这两天做了点小调整，导致 Gitee Pages Action 的报错，已修复，再 re-run 试试哈 @Kaiyiwing

**Comment by Kaiyiwing** [comment]
> Gitee 网站这两天做了点小调整，导致 Gitee Pages Action 的报错，已修复，再 re-run 试试哈 @Kaiyiwing

已经部署成功啦！非常感谢
