### ISSUE TITLE
关于公私钥匙对的问题

### ISSUE THREAD

**Issue by Brannua** [yanglbme/gitee-pages-action#43]
大佬您好，我仔细阅读了您的文档，并翻阅了所有关闭的 issues，没有找到答案，所以开了个新 issue 想向您请教

是这样的

0. 我使用的平台：Linux x86_64

1. 我平时使用 ssh 的方式在我本地和 github 之间进行操作，所以我的本地和 github 帐号配置好了一对用于 ssh 加密通信的公私钥

2. 我使用 hexo 发布博客，我的 github 帐号中有两个存储仓库，一个私有库是我的 hexo 博客源码，一个公开仓库是 hexo build 生成的静态站点，我的 hexo 博客源码仓库中配置了 github actions 实现博客站点的自动部署，所以这两个仓库之间的通信使用了我配置的另外一对公私钥对

3. 现在我想让我博客源码仓库中的 github actions 在 deploy 的时候，除了往我 github hexo 静态站点存储库中部署外，还往我 gitee 中的存储库中部署一份

4. 不好意思我没太读明白您写的文档中的一些地方，有以下几个问题，希望您给予指点，非常感谢

------

问题 1、按我理解您的文档中说的应该是博客站点只有一个仓库，您是指把生成的静态站点部署到和博客源码不同的分支；但是由于我是使用不同仓库存放博客源码和生成的静态博客（均使用 master 分支），所以我理解即使你想将静态博客同步部署到多个平台，也只需在其中一个平台上有一个博客源码仓库即可，然后你想部署的每个平台有一个静态站点的存储库即可，请问我这样理解对吗？

问题 2、在您的文档中，我理解您在「密钥的配置步骤」中第 1 步生成的公私钥对是为了能让 github 博客源码仓库把 build 出来的静态站点 push 一份到 gitee 的仓库中；如果是这样话，我就不理解您第 3 步说让「在 GitHub 的个人设置页面配置 SSH 公钥」的目的是什么了，想请教您一下

问题 3、您文档中第 4 步，为什么是将公钥配置到 gitee 账户全局，而不是指定的仓库中，因为我理解是 github 的博客源码仓库和 gitee 的静态站点仓库之间加密通信

真抱歉打扰您，希望您能不吝提供帮助，非常感谢！

**Comment by yanglbme** [comment]
@Brannua 你好

### 关于源码库与静态站点存储库

源码库可以只有一份，如果需要在多个平台上都进行部署，那么每个平台都需要静态站点存储库。

目前我这里是”源码+站点“是同一个库，我同步的时候，直接同步这个库就行。

### 关于第 3 步在 GitHub 配置 SSH 公钥的问题

Gitee / GitHub 都配置了公钥，本地的代码可以通过 SSH 方式直接 push 到对应的远程仓库。从本地 -> GitHub，如果此前已配置过，那么无需重复配置。

### 关于公钥的全局配置问题

如果只是想同步一个特定项目，那么在特定的仓库中配置应该就 ok。对于我而已，我需要将我帐号下的多个项目都进行同步，所以采用了全局配置的方式，这样省去一些重复配置的操作。如果用户也需要同步多个项目，那么建议采用跟我一样的方式。

**Comment by Brannua** [comment]
> @Brannua 你好
> 
> ### 关于源码库与静态站点存储库
> 源码库可以只有一份，如果需要在多个平台上都进行部署，那么每个平台都需要静态站点存储库。
> 
> 目前我这里是”源码+站点“是同一个库，我同步的时候，直接同步这个库就行。
> 
> ### 关于第 3 步在 GitHub 配置 SSH 公钥的问题
> Gitee / GitHub 都配置了公钥，本地的代码可以通过 SSH 方式直接 push 到对应的远程仓库。从本地 -> GitHub，如果此前已配置过，那么无需重复配置。
> 
> ### 关于公钥的全局配置问题
> 如果只是想同步一个特定项目，那么在特定的仓库中配置应该就 ok。对于我而言，我需要将我帐号下的多个项目都进行同步，所以我直接用全局配置的方式，这样省去一些重复配置的操作。如果用户也需要同步多个项目，那么建议采用跟我一样的方式。

懂了。非常感谢您！

**Comment by Brannua** [comment]
@yanglbme 抱歉大佬又打扰您, 想麻烦问一下, 如果把博客站点源码和编译生成的静态博客放在同一个仓库的不同分支, 由于想免费使用 pages 服务就必须是开源仓库, 那博客站点源码中配置文件中的私密信息如何隐藏 ? 比如我的站点就使用了 valine 评论系统 , 我的博客站点源码中就配置了该评论系统的 appId 和 key, 这两个信息我是不想对外暴露的, 有什么方便的解决办法吗 ? 期待您回复, 谢谢 !

**Comment by yanglbme** [comment]
这个可以看看 valine 官方有没有解决方案哈，我看了下他们的文档，如果是数据安全问题，好像是要配置安全域名。

**Comment by Brannua** [comment]
> 这个可以看看 valine 官方有没有解决方案哈，我看了下他们的文档，如果是数据安全问题，好像是要配置安全域名。

好的，谢谢大佬
