### ISSUE TITLE
Error: 120 bytes needed for message, but there is only space for 117

### ISSUE THREAD

**Issue by fjc0k** [yanglbme/gitee-pages-action#44]
![image](https://user-images.githubusercontent.com/13151189/142985828-cd1aa91c-c18f-40b0-9f79-7fad968523df.png)

https://github.com/fjc0k/yapi-to-typescript/runs/4296051414?check_suite_focus=true

**Comment by yanglbme** [comment]
我这边目前都是正常的，我排查一下

**Comment by yanglbme** [comment]
@fjc0k 有可能是你的 Gitee 密码长度过长，导致 RSA 加密失败，你将密码缩减 3个字符试试？

**Comment by fjc0k** [comment]
@yanglbme 赞 成功了 👍
