### ISSUE TITLE
好像hexo还不能自动部署

### ISSUE THREAD

**Issue by SiMaLaoShi** [yanglbme/gitee-pages-action#45]
从Github的站点是能自动部署，Gitee上也收到了deploy 通知，根据issue34的方案也设置了，还是不能够自动更新，需要手动到pages服务器下去更新一下，文件什么的都已经同步到Gitee了，就是blog还是旧的。

**Comment by SiMaLaoShi** [comment]
![image](https://user-images.githubusercontent.com/28924681/147310912-65e82dc4-a4e3-4c3b-b05d-cef5d1bd2939.png)

**Comment by yanglbme** [comment]
@SiMaLaoShi 你的配置文件在哪里？

**Comment by SiMaLaoShi** [comment]
action脚本吗，secrets配置是没问题的

**Comment by yanglbme** [comment]
是的

**Comment by yanglbme** [comment]
是在本地运行吗

**Comment by SiMaLaoShi** [comment]
不是，直接在github触发运行了，和直接在仓库action运行都不能更新，但是执行是通过了，gitee上也通知了

**Comment by SiMaLaoShi** [comment]
name: Sync
on: 
  page_build:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: https://github.com/SiMaLaoShi/simalaoshi.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:simalaoshi/simalaoshi.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: simalaoshi
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: simalaoshi/simalaoshi.git
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master

**Comment by SiMaLaoShi** [comment]
![image](https://user-images.githubusercontent.com/28924681/147313813-410009e7-f168-4e74-8027-f35736abb30d.png)
直接复制md上修改的

**Comment by yanglbme** [comment]
收到通知，说明部署自动触发了，可以还在部署中；另外部署后需要刷新浏览器缓存。

@SiMaLaoShi 这个确认一下哈。

**Comment by SiMaLaoShi** [comment]
不是，我昨天就测试过同步，我很久之前用过这个action，当时好像是正常，用的不多没在意，昨天测试一下发现没同步，到今天也是还没同步，早上过来也验证一下没同步，但是使用Gitee的Pages更新过一会就同步了，已经换电脑、’手机测试blog也是旧的。

**Comment by yanglbme** [comment]
gitee-repo 用 simalaoshi/simalaoshi 试试，我们使用这个参数的时候，是没带 `.git` 后缀的 @SiMaLaoShi

**Comment by SiMaLaoShi** [comment]
![image](https://user-images.githubusercontent.com/28924681/147331367-a33441fc-b74e-4c2d-a1b3-49ff66dad77c.png)
刚刚测试了一下好像还是不行，我在线执行一下再测试一下看下

**Comment by yanglbme** [comment]
好的，那你试下。我这边很多项目都在用 Gitee Pages Action，是正常的

**Comment by SiMaLaoShi** [comment]
好像可以，我周五晚上看还不行，周一就行了，这个周期好像很长，但是用gitee的手动更新一下就行了，暂时不知道什么原因

**Comment by SiMaLaoShi** [comment]
今天再测试一下，看下明天是不是会同步到

**Comment by yanglbme** [comment]
嗯嗯好的，我这边一直在用，没发现问题

**Comment by SiMaLaoShi** [comment]
可以了，可能上次构建部署刷新比较慢，今天一下就更新出来了
