### ISSUE TITLE
action使用问题

### ISSUE THREAD

**Issue by MuYanustc** [yanglbme/gitee-pages-action#48]
![屏幕截图 2022-02-01 154458](https://user-images.githubusercontent.com/56762019/151930555-6f430adf-bb75-49fa-9bf0-3c16be285780.png)
![屏幕截图 2022-02-01 154650](https://user-images.githubusercontent.com/56762019/151930556-b0993f67-5345-4705-9d7d-d66f35fea053.png)
![屏幕截图 2022-02-01 154715](https://user-images.githubusercontent.com/56762019/151930558-a80ffdc3-7d04-4b19-b9a5-c74218ebb00b.png)
如上三图所示，我很疑惑，为什么没有触发action呢？

**Comment by MuYanustc** [comment]
好像可以了....是因为没加s........

**Comment by yanglbme** [comment]
哈哈，那就好
