### ISSUE TITLE
关于 readme 文档的一些建议

### ISSUE THREAD

**Issue by AlbertLei** [yanglbme/gitee-pages-action#49]
您好, 感谢提供这个 action. 我已经同步成功, 但踩了一些坑. 有一些是 readme 文档里没有提到的, 或许对其他人有用.

1. ssh-keygen 使用参数 `-m PEM`

我按照 readme 教程的命令 `ssh-keygen -t rsa -C`, 试了很多次. 始终不成功. 谷歌后, 在这个[SO回答](https://stackoverflow.com/a/59515175) 的建议下, 强制使用 PEM 格式, 然后就成功了.

我的操作系统是 mac 10.15.7, 用的是系统自带的 `ssh-keygen` 命令.

这个问题困扰了我很久. 我之前没接触过 ssh, 还以为是复制粘贴中出了问题, 费了很多时间.

2. 同步页面需要绑定 gitee 微信公众号

这是个小问题, 因为error 信息里写的很清楚. 但在 readme 的开始就写上或许会更好.

再次感谢

**Comment by yanglbme** [comment]
@AlbertLei 感谢你的反馈。

- 第一个问题，确实可能环境不同，生成 ssh key 也有所差别，这个接下来会在 readme 中补充；
- 第二个问题，绑定 gitee 公众号，我目前是在 readme 错误及解决方案第 4 点中说明。

再次感谢你，有任何的问题，欢迎随时提 issues。
