### ISSUE TITLE
能否在coding的持续集成中使用

### ISSUE THREAD

**Issue by kkfive** [yanglbme/gitee-pages-action#50]
最近一段时间不知道为什么，GitHub向Gitee推送代码时特别的慢。

因此想在coding中去构建并推送到gitee

**Comment by yanglbme** [comment]
这个不支持哈，我们这个 action 属于 GitHub 的功能特性

**Comment by kkfive** [comment]
> 这个不支持哈，我们这个 action 属于 GitHub 的功能特性

好吧
