### ISSUE TITLE
是否有办法提供参数强制刷新gitee pages

### ISSUE THREAD

**Issue by kailong321200875** [yanglbme/gitee-pages-action#51]
因为目前同步过去，gitee pages 部署的静态页面是不会强制更新的，需要手动去触发更新，这个是比较麻烦的。不知道gitee 是否有提供相应的api可供调用

**Comment by yanglbme** [comment]
是说 Gitee Pages 已经部署成功了，但页面由于缓存等原因，没有实时刷新？

**Comment by kailong321200875** [comment]
> 是说 Gitee Pages 已经部署成功了，但页面由于缓存等原因，没有实时刷新？

好像是因为gitee pages 不会主动去更新，需要手动在强制更新下。github pages 是可以同步更新的

**Comment by yanglbme** [comment]
你用 shift+f5 刷新浏览器缓存估计就可以了

**Comment by kailong321200875** [comment]
> 你用 shift+f5 刷新浏览器缓存估计就可以了

不行的，gitee pages 的问题，就是不知道是否可以有api可以直接调用强制刷新的接口

**Comment by yanglbme** [comment]
使用 Gitee Pages Action，就可以做到自动部署更新哈
