### ISSUE TITLE
Error: [2022-05-22 09:23:40] HTTPSConnectionPool(host='gitee.com', port=443): Read timed out. (read timeout=6)

### ISSUE THREAD

**Issue by nmydt** [yanglbme/gitee-pages-action#52]
Error: [2022-05-22 09:23:40] HTTPSConnectionPool(host='gitee.com', port=443): Read timed out. (read timeout=6)
有时会出现这种错误，出现错误时能再运行一次吗，不用自己手动运行了

**Comment by yanglbme** [comment]
目前是有重试机制的，不过偶尔还是会超时问题。

我想办法再优化一下看看

**Comment by nmydt** [comment]
好的，谢谢
