### ISSUE TITLE
卡在Warning: Permanently added 'github.com' (ED25519) to the list of known hosts. 动不了

### ISSUE THREAD

**Issue by iwyang** [yanglbme/gitee-pages-action#53]
DRY RUN=false
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
Warning: Permanently added 'gitee.com' (ED25519) to the list of known hosts.

**Comment by yanglbme** [comment]
这个还没到 gitee pages action 的运行呢，还在进行代码同步中。有时候同步会比较慢。

**Comment by yanglbme** [comment]
可以手动 cancel 然后 rerun 试试

**Comment by yanglbme** [comment]
今天 GitHub 和 Gitee 之间的通信好像确实有点问题，有时候同步代码会卡住，有时候能成功。

> 我这个也卡住了 https://github.com/doocs/source-code-hunter/runs/6814757442?check_suite_focus=true

平常基本没啥问题。

**Comment by iwyang** [comment]
谢谢解答
