### ISSUE TITLE
关于 gitee-repo 中的 Gitee 仓库命名问题

### ISSUE THREAD

**Issue by Xsakura1314** [yanglbme/gitee-pages-action#54]
作者你好

今天我在使用同步配置的时候提示让我检查 Gitee 仓库的命名：

> Error: Deploy error occurred, please check your input `gitee-repo`.

我的 `yml` 中的配置是：

> gitee-repo: Tmiszy/blog

在 Gitee 中的显示也是一样的

![image](https://user-images.githubusercontent.com/59106419/177025052-33e3ed81-8001-4df2-8c50-93d989b05c7c.png)

这两个的配置都是一致的，为什么会还会提示有问题呢？

**Comment by Xsakura1314** [comment]
已解决。

注意：

`gitee-repo` 实际填写的是打开对应的 Gitee 仓库以后，在 URL 中会显示的字符串 `https://gitee.com/用户名/XXX`，而这里 `用户名/XXX` 才是要填写的东西。

在 Gitee 中，仓库名称与路径不一定一致，以实际的路径为准（坑爹呢这不是）。

![image](https://user-images.githubusercontent.com/59106419/177026109-aeee6bee-bf7e-4f67-8709-99e97ad777bd.png)

如果作者看到的话，希望可以再详细强调一下

**Comment by yanglbme** [comment]
谢谢反馈，我接下来在 README 中补充说明一下
