### ISSUE TITLE
错误信息: Pages 部署失败，/css/hbe.style.css 文件可能包含违禁违规内容，请排查调整后再行重试

### ISSUE THREAD

**Issue by cheng-qiang** [yanglbme/gitee-pages-action#55]
错误信息: Pages 部署失败，chengqiangxj/chengqiangxj/css/hbe.style.css 文件可能包含违禁违规内容，请排查调整后再行重试

怎么排除。。。。。。

**Comment by yanglbme** [comment]
这个应该是被 Gitee 官方误判了，不是这个 action 工具能控制的哈
