### ISSUE TITLE
请问公私钥会存在过期问题吗？

### ISSUE THREAD

**Issue by BenjiaH** [yanglbme/gitee-pages-action#56]
稳定使用了一个月（最近一次正常使用是8月12日），今天突然提示无法访问仓库。
![image](https://user-images.githubusercontent.com/46958476/184604600-46da3e92-7270-4fce-bcd0-667fb4373379.png)
![image](https://user-images.githubusercontent.com/46958476/184604642-1fa2d864-8dd0-49bd-8267-9447df246347.png)

**Comment by yanglbme** [comment]
re-run 试试，看是不是还有问题

**Comment by yanglbme** [comment]
同步过程有时候会失败（一般 re-run 能解决），同步是用的 `wearerequired/git-mirror-action@master` 这个 action

Gitee Pages Action 是用来实现自动部署。

**Comment by BenjiaH** [comment]
> 同步过程有时候会失败（一般 re-run 能解决），同步是用的 `wearerequired/git-mirror-action@master` 这个 action
> 
> Gitee Pages Action 是用来实现自动部署。

re-run了三次，这下成功了

**Comment by yanglbme** [comment]
好的，谢谢反馈。我这边更新一下错误与解决方案，遇到这个错误，先尝试 re-run

**Comment by BenjiaH** [comment]
> 好的，谢谢反馈。我这边更新一下错误与解决方案，遇到这个错误，先尝试 re-run

不客气，谢谢带来了很好用的action
