### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by GuoJuna** [yanglbme/gitee-pages-action#6]
gitee会收到短信验证码,要怎么处理呢

**Comment by yanglbme** [comment]
登录的短信验证码？我目前自动部署都是正常的。

![image](https://user-images.githubusercontent.com/21008209/88261803-91026e00-ccf9-11ea-8e76-2cec414c02b3.png)

**Comment by guojun49** [comment]
是的,收到短信验证码,提示异地登陆; 我看能不能解绑手机试下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午3:32
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
登录的短信验证码？我目前自动部署都是正常的。

**Comment by yanglbme** [comment]
好的，有问题随时反馈。

**Comment by guojun49** [comment]
解绑手机又收到邮件验证码 
![image](https://user-images.githubusercontent.com/23692022/88264066-b8f3d080-ccfd-11ea-9a83-9a72207d81ca.png)

**Comment by yanglbme** [comment]
你试一下在 Gitee 官网上登录，如果需要验证码，就输入确认登录。之后再试一下用 Gitee Pages Action。

**Comment by guojun49** [comment]
gitee 官网登陆不需要验证码,这是异地登陆验证码







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:03
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
你试一下在 Gitee 官网上登录，如果需要验证码，就输入确认登录。之后再试一下用 Gitee Pages Action。
 
&mdash;

**Comment by yanglbme** [comment]
你有没有办法能让你的号在异地登录一下，比如 VPN? 然后过一下验证，之后应该就可以了。

或者 Gitee Pages Action 新增一个 cookies 登录的支持。但是 cookies 会有有效期限制，一旦失效，需要再手动更新 cookies。

**Comment by guojun49** [comment]
好的 这个没弄过,我试下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:11
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
你有没有办法能让你的号在异地登录一下，比如 VPN? 然后过一下验证，之后应该就可以了。
 
或者 Gitee Pages Action 新增一个 cookies 登录的支持。但是 cookies 会有有效期限制，一旦失效，需要再手动更新 cookies。

**Comment by guojun49** [comment]
提示登陆好了,但是好像内容没有更新
![image](https://user-images.githubusercontent.com/23692022/88265993-03c31780-cd01-11ea-8dbc-cc30ad808807.png)

**Comment by yanglbme** [comment]
你目前是将 Gitee Pages Action 应用在哪里？

**Comment by guojun49** [comment]
github上,用来同步到gitee,然后更新部署




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:29
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
你目前是将 Gitee Pages Action 应用在哪里？
 
&mdash;

**Comment by yanglbme** [comment]
你的 workflow 配置在哪里？

**Comment by guojun49** [comment]
https://github.com/guojun49/vue-blog




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:33
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
你的 workflow 配置在哪里？

**Comment by yanglbme** [comment]
![image](https://user-images.githubusercontent.com/21008209/88267289-3837d300-cd03-11ea-880f-d0f015a816bc.png)

首次先手动登录 Gitee 部署一下。试试。

**Comment by yanglbme** [comment]
![image](https://user-images.githubusercontent.com/21008209/88267482-7af9ab00-cd03-11ea-90df-6879f568f730.png)

为什么我访问不了你的项目，这样外界能访问吗？你 Gitee 必须先有项目，之后才能做同步并自动部署。

**Comment by guojun49** [comment]
地址不对 这个https://guojun49.gitee.io/



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:43
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 

 
为什么我访问不了你的项目，这样外界能访问吗？你 Gitee 必须先有项目，之后才能做同步并自动部署。
 
&mdash;

**Comment by guojun49** [comment]
这个构建是需要手动点一次这个更新的意思吗?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:41
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 

 
首次先手动登录 Gitee 部署一下。试试。
 
&mdash;

**Comment by yanglbme** [comment]
我没看到你的 Gitee 仓库。

首次才需要，之后都会自动部署。

**Comment by guojun49** [comment]
https://gitee.com/guojun49/guojun49




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:51
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
我没看到你的 Gitee 仓库。
 
首次才需要，之后都会自动部署。

**Comment by guojun49** [comment]
https://gitee.com/guojun49/guojun49&nbsp;在这里 你看下哪里有什么问题吗,代码同步过来了,但是没有更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:51
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
我没看到你的 Gitee 仓库。
 
首次才需要，之后都会自动部署。

**Comment by guojun49** [comment]
好像好了, 谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:51
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
我没看到你的 Gitee 仓库。
 
首次才需要，之后都会自动部署。

**Comment by yanglbme** [comment]
👍

**Comment by guojun49** [comment]
这个仓库私有有关系吗? 也许还是缓存的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午4:51
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
我没看到你的 Gitee 仓库。
 
首次才需要，之后都会自动部署。

**Comment by yanglbme** [comment]
私有仓库的话，不影响 Gitee Pages Action 的正常工作，因为这个 Action 的本质是用程序代替人工去登录 Gitee 并自动点击部署。

当 Action 运行完，只是意味着按钮点击了，此时 Gitee Pages 可能正在部署中，需要过一会儿才生效。

**Comment by guojun49** [comment]
那开始就应该是缓存问题&nbsp; 现在舒服了 谢谢大佬提供这么厉害的工具




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午5:12
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
私有仓库的话，不影响 Gitee Pages Action 的正常工作，因为这个 Action 的本质是用程序代替人工去登录 Gitee 并自动点击部署。
 
当 Action 运行完，只是意味着按钮点击了，此时 Gitee Pages 可能正在部署中，需要过一会儿才生效。
 
&mdash;

**Comment by yanglbme** [comment]
我最初是因为自己有好几个 GitHub 仓库需要同步部署到 Gitee Pages，手动操作很繁琐，所以开发了这个 Action。现在也能够为他人带来便利，那就更好了。

谢谢你的使用，若之后有使用上的问题，欢迎随时反馈。

**Comment by guojun49** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Libin"<notifications@github.com&gt;; 
发送时间: 2020年7月23日(星期四) 下午5:22
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
我最初是因为自己有好几个 GitHub 仓库需要同步部署到 Gitee Pages，手动操作很繁琐，所以开发了这个 Action。现在也能够为他人带来便利，那就更好了。
 
谢谢你的使用，若之后有使用上的问题，欢迎随时反馈。
 
&mdash;

**Comment by baizixv** [comment]
@guojun49  所以最后到底是做了什么操作解决的问题？ 我现在也碰上自动部署的时候发短信验证码的问题了。

**Comment by guojun49** [comment]
可以先绑定下微信公众号,如果还不行就尝试下异地IP等录下吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "baizixv"<notifications@github.com&gt;; 
发送时间: 2020年7月28日(星期二) 下午2:16
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
@guojun49  所以最后到底是做了什么操作解决的问题？ 我现在也碰上自动部署的时候发短信验证码的问题了。

**Comment by baizixv** [comment]
@guojun49 是用gitee绑定微信公众号么？ 绑定的又是什么微信公众号？码云？

**Comment by guojun49** [comment]
&nbsp;微信绑定gitee微信公众号



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "baizixv"<notifications@github.com&gt;; 
发送时间: 2020年7月28日(星期二) 下午2:40
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
@guojun49 是用gitee绑定微信公众号么？ 绑定的又是什么微信公众号？码云？
 
&mdash;

**Comment by baizixv** [comment]
@guojun49  十分感谢！经过验证，绑定微信公众号解决了问题。

**Comment by guojun49** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "baizixv"<notifications@github.com&gt;; 
发送时间: 2020年7月28日(星期二) 下午2:49
收件人: "yanglbme/gitee-pages-action"<gitee-pages-action@noreply.github.com&gt;; 
抄送: "864350301"<864350301@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yanglbme/gitee-pages-action] 登陆失败 (#6)





 
@guojun49  十分感谢！经过验证，绑定微信公众号解决了问题。
 
&mdash;

**Comment by NoJsJa** [comment]
解决了，微信绑定gitee微信公众号是真的骚 :laughing:

**Comment by afc163** [comment]
好像还是有问题，已经绑定公众号还是报错：https://github.com/antvis/antvis.github.io/pull/92/checks?check_run_id=1419166453

**Comment by yanglbme** [comment]
@afc163 我查一下

**Comment by yanglbme** [comment]
看日志是登录成功了，脚本判断是否登录成功，需要完善一下

**Comment by yanglbme** [comment]
@afc163 麻烦再试试 ：）

**Comment by afc163** [comment]
好了

**Comment by luwanglin** [comment]
只需要绑定以下微信公众号就好了，哈哈，谢谢作者
