### ISSUE TITLE
error: failed to push some refs to 'gitee.com:hisnxg/hisnxg.git'

### ISSUE THREAD

**Issue by mynxg** [yanglbme/gitee-pages-action#60]
WARNING: StrictHostKeyChecking disabled
Cloning into bare repository 'hexo-theme-blog.git'...
SOURCE=git@github.com:hisnxg/hexo-theme-blog.git
DESTINATION=git@gitee.com:hisnxg/hisnxg.git
DRY RUN=false
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
Warning: Permanently added 'gitee.com' (ED25519) to the list of known hosts.
remote: Powered by GITEE.COM [GNK-6.4]        
remote: error: By default, deleting the current branch is denied, because the next        
remote: 'git clone' won't result in any file checked out, causing confusion.        
remote: 
remote: You can set 'receive.denyDeleteCurrent' configuration variable to        
remote: 'warn' or 'ignore' in the remote repository to allow deleting the        
remote: current branch, with or without a warning message.        
remote: 
remote: To squelch this message, you can set it to 'refuse'.        
remote: error: refusing to delete the current branch: refs/heads/gh-pages        
To gitee.com:hisnxg/hisnxg.git
 + 2f6ae77...2[17](https://github.com/hisnxg/hexo-theme-blog/actions/runs/3314771186/jobs/5474486324#step:4:18)d2a4 main -> main (forced update)
 * [new branch]      dependabot/npm_and_yarn/hexo-6.3.0 -> dependabot/npm_and_yarn/hexo-6.3.0
 * [new branch]      dependabot/npm_and_yarn/hexo-generator-archive-2.0.0 -> dependabot/npm_and_yarn/hexo-generator-archive-2.0.0
 * [new branch]      dependabot/npm_and_yarn/hexo-generator-category-2.0.0 -> dependabot/npm_and_yarn/hexo-generator-category-2.0.0
 * [new branch]      dependabot/npm_and_yarn/hexo-generator-index-3.0.0 -> dependabot/npm_and_yarn/hexo-generator-index-3.0.0
 * [new branch]      dependabot/npm_and_yarn/hexo-generator-tag-2.0.0 -> dependabot/npm_and_yarn/hexo-generator-tag-2.0.0
 * [new branch]      dependabot/npm_and_yarn/hexo-renderer-marked-6.0.0 -> dependabot/npm_and_yarn/hexo-renderer-marked-6.0.0
 * [new branch]      master -> master
 ! [remote rejected] gh-pages (deletion of the current branch prohibited)
error: failed to push some refs to 'gitee.com:hisnxg/hisnxg.git'

**Comment by mynxg** [comment]
![image](https://user-images.githubusercontent.com/77525803/197588602-bd281911-3cdf-49f8-95b6-26d330fd7978.png)
错误如上图，在github action时出现这样的错误

**Comment by yanglbme** [comment]
![image](https://user-images.githubusercontent.com/21008209/197662033-4abbe804-03e9-410c-9cd1-6705cb77776a.png)

你这里要删除 gh-pages 分支吧，但 Gitee 不允许，可能你 Gitee 仓库把 gh-pages 作为默认分支导致？

**Comment by mynxg** [comment]
![image](https://user-images.githubusercontent.com/77525803/197689986-7b5fdbc8-5505-4365-93e8-5447b96fedb8.png)
是设置为了默认分支导致的。我想部署到gh-pages分支 ，但它想要删除gh-pages，我如何解决呢？
还有就是它部署到gitee上的是我的源代码，而不是构建的后的静态页面。这是为什么呢？

**Comment by mynxg** [comment]
![image](https://user-images.githubusercontent.com/77525803/197690975-55fa13bd-66da-47fb-97e4-8ef359600f6e.png)

**Comment by mynxg** [comment]
![image](https://user-images.githubusercontent.com/77525803/197691111-1c7ed39f-661c-4b70-961a-2f360b1a7c0c.png)

**Comment by mynxg** [comment]
![image](https://user-images.githubusercontent.com/77525803/197691188-be18b80d-f6c7-4696-a10b-15e22cfc63c9.png)
部署上去的都是源代码，不是构建后的代码，很困惑

**Comment by mynxg** [comment]
![image](https://user-images.githubusercontent.com/77525803/197692040-02deed2a-4e00-47a8-82e4-9c78af6133fb.png)
执行gh-pages分支被自动删除了

**Comment by mynxg** [comment]
![image](https://user-images.githubusercontent.com/77525803/197692146-02520976-ef34-4a95-87cb-49173a945bee.png)
这是构建成功了，但仓库没看到构建后的静态页面

**Comment by mynxg** [comment]
我明白了，github将代码部署到gitee仓库后，选择需要部署的分支，它会将源代码自动构建。
![image](https://user-images.githubusercontent.com/77525803/197692802-a20e6c79-a00e-4a11-8c44-ff52990b1d00.png)

**Comment by yanglbme** [comment]
现在还有问题吗

**Comment by mynxg** [comment]
没有了，非常感谢
