### ISSUE TITLE
关于使用 ED25519 算法生成的SSH密匙

### ISSUE THREAD

**Issue by Wu-JunHui** [yanglbme/gitee-pages-action#62]
大佬你好，我本地电脑使用的是 ED25519 算法的 SSH 密匙，可正常在 GitHub 和 Gitee 的仓库中通过 SSH 进行 Git 操作
在按 README 进行相关密匙配置后，工作流报了以下错误：

Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
Load key "/root/.ssh/id_rsa": error in libcrypto
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

不知我理解的有没有错误：git-mirror-action 就是将 SSH 私钥给予 GitHub Actions 以获取访问 GitHub 仓库的权限，但如果不是 rsa 算法生成的 SSH 密匙就会报错吗？是不是只能使用 rsa 算法的 ssh 密匙？

我翻了 git-mirror-action 以及 当前 action  的 issues 都没找到答案，也知道这问题不属于 gitee-pages-action，但奈何小弟学艺不精，只能看看这里能不能找到答案，谢谢大佬百忙当中处理 issues

**Comment by Wu-JunHui** [comment]
找到问题所在了，是我自己复制私钥的时候，以为以下两行是注释就没复制
-----BEGIN OPENSSH PRIVATE KEY-----
-----END OPENSSH PRIVATE KEY-----
让人尴尬的操作

谢谢您的 action！祝您前程似锦

**Comment by yanglbme** [comment]
棒，解决了就好，也谢谢你的经验分享
