### ISSUE TITLE
Deploy error occurred, please check your input `gitee-repo`.

### ISSUE THREAD

**Issue by 1226085293** [yanglbme/gitee-pages-action#65]
之前好好的，今天上传 markdown 后忽然出现这个错误，gitee 账号和仓库名没有任何改变，仓库地址是 https://github.com/1226085293/1226085293.github.io

**Comment by yanglbme** [comment]
我这边试了，脚本可以正常登录

**Comment by 1226085293** [comment]
> 我这边试了，脚本可以正常登录

问题是出现了这个问题，而且我重复尝试了一次，依旧出现，不知道什么原因导致的，之前是可以成功运行的，不知道是否和我新上传的文档有关

**Comment by 1226085293** [comment]
我今晚上排除法试试

**Comment by yanglbme** [comment]
好的，你试试。或者你方便的话，私下提供个账号给我试试？后面你可以修改账号信息，我不会用你的

**Comment by 1226085293** [comment]
解决了，手动构建 gitee pages 一次就行了，gitee 的毛病

**Comment by yanglbme** [comment]
好的
