### ISSUE TITLE
SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by shenweiyan** [yanglbme/gitee-pages-action#66]
gitee-pages-action 好像出问题了！

![image](https://github.com/yanglbme/gitee-pages-action/assets/26101369/abebcd41-277e-4f46-9741-1bce803fe935)

**Comment by yanglbme** [comment]
我看看，稍等

**Comment by yanglbme** [comment]
刚才改了点东西

**Comment by shenweiyan** [comment]
> 刚才改了点东西

[main.py](https://github.com/yanglbme/gitee-pages-action/blob/main/main.py) 这里出问题：`f"📕 Getting Started Guide: {marketplace}\"`

**Comment by yanglbme** [comment]
好的，我改过来了，你重跑一下试试？

**Comment by shenweiyan** [comment]
> 好的，我改过来了，你重跑一下试试？

好了，恢复正常了，感谢~
