### ISSUE TITLE
action第一步同步正常,第二步从昨天开始就一直失败

### ISSUE THREAD

**Issue by Minry** [yanglbme/gitee-pages-action#67]
![image](https://github.com/yanglbme/gitee-pages-action/assets/20706163/51bb0c9a-8ee6-4311-a4b0-dfba6b1512ca)

**Comment by yanglbme** [comment]
我的也超时了，晚点我看看

**Comment by Minry** [comment]
谢谢大佬~

**Comment by yanglbme** [comment]
现在是可以的，应该是 Gitee 不稳定导致，你可以 rerun 试试

**Comment by Minry** [comment]
ok,我的也恢复啦! 
Thanks♪(･ω･)ﾉ
