### ISSUE TITLE
这种能实现吗

### ISSUE THREAD

**Issue by Farb** [yanglbme/gitee-pages-action#69]
我的源码在GitHub main分支，依靠github-action自动部署到gh-page分支。我只想将gh-page分支生成的静态的网站同步到gitee的master分支去部署。这种可以实现吗？看您的配置，没有看到源的分支，只看到了部署的目标分支。

**Comment by yanglbme** [comment]
这个属于代码同步的问题噢，可以看看有没有相关的 action
