### ISSUE TITLE
 Sync to Gitee这步报错了 

### ISSUE THREAD

**Issue by zerofo** [yanglbme/gitee-pages-action#9]
Warning: Permanently added 'github.com,x.x.x.x' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by zerofo** [comment]
是产生一个 公钥 放 gitee ssh .. 私钥放github  secret 吗?

**Comment by zerofo** [comment]
解决了   公钥 放Deploy keys

**Comment by Alanhays** [comment]
> 解决了 公钥 放部署密钥

谢谢，帮我接解决了问题。
